apiVersion: v1
kind: ConfigMap
metadata:
  name: notary-portal-config
data:
  NODE_ENV: production
  PORT: '3000'
  LOG_LEVEL: info
  FIAS_PROVIDER: stub
  MAIL_TRANSPORT: log
  CORS_ORIGIN: http://localhost:8080
  FRONTEND_URL: http://localhost:8080
  PAYMENT_PROVIDER: robokassa
  ROBOKASSA_TEST_MODE: 'true'
  S3_ENDPOINT: http://minio:9000
  S3_REGION: us-east-1
  S3_FORCE_PATH_STYLE: 'true'
  S3_BUCKET_PAYMENT_DOCUMENTS: payment-documents
  S3_BUCKET_ASSESSMENT_FILES: assessment-files
