apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notary-portal
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
spec:
  ingressClassName: nginx
  rules:
    - host: notary.local
      http:
        paths:
          - path: /health
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /metrics
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /notary.
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
