resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - postgres.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
  - migrate-job.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - monitoring.yaml

namespace: notary-portal

images:
  - name: notary-portal-api
    newName: notary-portal-api
    newTag: local
  - name: notary-portal-web
    newName: notary-portal-web
    newTag: local
