apiVersion: v1
kind: ServiceAccount
metadata:
  name: notary-api
  labels:
    app.kubernetes.io/name: notary-portal
    app.kubernetes.io/component: api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notary-web
  labels:
    app.kubernetes.io/name: notary-portal
    app.kubernetes.io/component: web
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notary-migrate
  labels:
    app.kubernetes.io/name: notary-portal
    app.kubernetes.io/component: migrate
automountServiceAccountToken: false
