sonar.projectKey=notary-portal
sonar.projectName=Notary Portal
sonar.sourceEncoding=UTF-8

sonar.sources=apps,libs
sonar.tests=apps,libs
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/generated/**,**/*.pb.ts,**/*.connect.ts,archive/**,outputs/**
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/**/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.base.json,apps/api/tsconfig.json,apps/web/tsconfig.json
