apiVersion: v2
name: notary-portal
description: Helm chart for the Notary Portal API, Web, Postgres and migration job.
type: application
version: 0.1.0
appVersion: 1.1.1
home: https://github.com/eaafit/WebDevelopment
sources:
  - https://github.com/eaafit/WebDevelopment
keywords:
  - notary
  - nx
  - angular
  - nestjs
  - kubernetes
maintainers:
  - name: eaafit
    email: devops@example.com
