{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "notary-portal.fullname" . }}
  labels:
    {{- include "notary-portal.componentLabels" (dict "root" . "component" "ingress") | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range .Values.ingress.apiExactPaths }}
          - path: {{ . }}
            pathType: Exact
            backend:
              service:
                name: {{ include "notary-portal.fullname" $ }}-api
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
          {{- range .Values.ingress.apiPrefixPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "notary-portal.fullname" $ }}-api
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "notary-portal.fullname" . }}-web
                port:
                  number: {{ .Values.web.service.port }}
{{- end }}
