{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notary-portal.secretName" . }}
  labels:
    {{- include "notary-portal.componentLabels" (dict "root" . "component" "secret") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
