{{- if and .Values.api.enabled .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notary-portal.apiServiceAccountName" . }}
  labels:
    {{- include "notary-portal.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
automountServiceAccountToken: {{ .Values.api.serviceAccount.automountServiceAccountToken }}
---
{{- end }}
{{- if and .Values.web.enabled .Values.web.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notary-portal.webServiceAccountName" . }}
  labels:
    {{- include "notary-portal.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
automountServiceAccountToken: {{ .Values.web.serviceAccount.automountServiceAccountToken }}
---
{{- end }}
{{- if and .Values.migrations.enabled .Values.migrations.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notary-portal.migrateServiceAccountName" . }}
  labels:
    {{- include "notary-portal.componentLabels" (dict "root" . "component" "migrate") | nindent 4 }}
automountServiceAccountToken: {{ .Values.migrations.serviceAccount.automountServiceAccountToken }}
{{- end }}
