{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notary-portal.fullname" . }}-web
  labels:
    {{- include "notary-portal.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
  selector:
    {{- include "notary-portal.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notary-portal.fullname" . }}-web
  labels:
    {{- include "notary-portal.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "notary-portal.selectorLabels" (dict "root" . "component" "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notary-portal.selectorLabels" (dict "root" . "component" "web") | nindent 8 }}
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.web.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "notary-portal.webServiceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          {{- include "notary-portal.image" (dict "root" . "image" .Values.web.image) | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          {{- if .Values.web.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.web.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
          {{- end }}
{{- end }}
