apiVersion: apps/v1
kind: Deployment
metadata:
  name: notary-api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notary-web
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 75m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 192Mi
