apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notary-api
spec:
  minReplicas: 2
  maxReplicas: 4
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notary-web
spec:
  minReplicas: 2
  maxReplicas: 4
