# Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
# Uncomment this line to enable task distribution
# - run: pnpm dlx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
# Prepend any command with "nx record --" to record its logs to Nx Cloud
# - run: pnpm exec nx record -- echo Hello World

name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm & Node
        uses: ./.github/actions/setup

      - name: Format
        run: pnpm exec nx affected -t format:check --parallel=3

      - name: Lint
        run: pnpm exec nx affected -t lint stylelint --parallel=3

  proto-quality:
    name: Contracts Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm & Node
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm exec nx affected -t lint-proto --parallel=3

      - name: Breaking Changes
        run: pnpm exec nx affected -t breaking-proto --parallel=3

  test-and-build:
    name: Test and Build
    needs: [code-quality, proto-quality]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm & Node
        uses: ./.github/actions/setup

      - name: Test
        run: pnpm exec nx affected -t test --parallel=3

      - name: Build
        run: pnpm exec nx affected -t build --parallel=3

  coverage:
    name: Test Coverage
    needs: [test-and-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm & Node
        uses: ./.github/actions/setup

      - name: Test with Coverage
        run: pnpm exec nx run-many -t test --parallel=3 --ci --coverage

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage

  frontend-deploy-artifact:
    name: Frontend Deployment Artifact
    needs: [test-and-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm & Node
        uses: ./.github/actions/setup

      - name: Build Web App
        run: pnpm exec nx build web

      - name: Upload Deployment Artifact
        uses: actions/upload-artifact@v3-node20
        with:
          name: web-dist
          path: dist/apps/web/browser
          if-no-files-found: error

  backend-deploy-artifact:
    name: Backend Deployment Artifact
    needs: [test-and-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm & Node
        uses: ./.github/actions/setup

      - name: Build Backend Deployment Bundle
        run: pnpm exec nx run api:prune

      - name: Upload Backend Deployment Artifact
        uses: actions/upload-artifact@v3-node20
        with:
          name: api-dist
          path: dist/apps/api
          if-no-files-found: error

  self-healing-ci:
    name: Self Healing CI
    needs: [code-quality, proto-quality, test-and-build, coverage, frontend-deploy-artifact, backend-deploy-artifact]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm & Node
        uses: ./.github/actions/setup

      - name: Self-Healing CI
        run: pnpm exec nx fix-ci
